In [132]:
import pandas as pd

In [133]:
pymoli1 = "purchase_data.json"
pymoli2 = "purchase_data2.json"

In [134]:
pymoli1_pd = pd.read_json(pymoli1)
pymoli2_pd = pd.read_json(pymoli2)

In [135]:
pymoli1_pd.head()

,Age,Gender,Item ID,Item Name,Price,SN
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46
2,34,Male,174,Primitive Blade,2.46,Assastnya25
3,21,Male,92,Final Critic,1.36,Pheusrical25
4,23,Male,63,Stormfury Mace,1.27,Aela59

In [136]:
pymoli2_pd.head()

   Age Gender  Item ID                 Item Name  Price          SN
0   20   Male       93  Apocalyptic Battlescythe   4.49     Iloni35
1   21   Male       12                     Dawne   3.36   Aidaira26
2   17   Male        5                Putrid Fan   2.63      Irim47
3   17   Male      123         Twilight's Carver   2.55     Irith83
4   22   Male      154              Feral Katana   4.11  Philodil43

In [137]:
player_count = len(pymoli1_pd) + len(pymoli2_pd)
player_countP = pd.DataFrame({"Total Player Count": [player_count]})
player_countP

   Total Player Count
0                 858

In [138]:
pymoli1_rename = pymoli1_pd.rename(columns={'Item ID': 'ItemID', 'Item Name': 'ItemName'})
pymoli2_rename = pymoli1_pd.rename(columns={'Item ID': 'ItemID', 'Item Name': 'ItemName'})

In [139]:
list(set(pymoli1_rename.ItemName))

['Mourning Blade',
 'Vindictive Glass Edge',
 'Heartseeker, Reaver of Souls',
 'Aetherius, Boon of the Blessed',
 'Curved Axe',
 'Conqueror Adamantite Mace',
 'Mercenary Sabre',
 'Thunderfury Scimitar',
 'Glimmer, Ender of the Moon',
 'Dreamkiss',
 'Warped Diamond Crusader',
 'Fury',
 'Alpha',
 'Righteous Might',
 'Yearning Crusher',
 'Soul Infused Crystal',
 'Lifebender',
 'Expiration, Warscythe Of Lost Worlds',
 'Retribution Axe',
 "Bloodlord's Fetish",
 'Heartstriker, Legacy of the Light',
 'Shadow Strike, Glory of Ending Hope',
 'Brimstone',
 "Dragon's Greatsword",
 'Brutality Ivory Warmace',
 'Lightning, Etcher of the King',
 'Glinting Glass Edge',
 'Serenity',
 'Interrogator, Blood Blade of the Queen',
 'Downfall, Scalpel Of The Emperor',
 'Hailstorm Shadowsteel Scythe',
 'Frenzied Scimitar',
 'Celeste, Incarnation of the Corrupted',
 'Piece Maker',
 'Soul-Forged Steel Shortsword',
 'Severance',
 'The Decapitator',
 'Swan Song, Gouger Of Terror',
 'Nirvana',
 'Darkheart',
 'Hellreaver, Heirloom of Inception',
 'Arcane Gem',
 'Pursuit, Cudgel of Necromancy',
 'Abyssal Shard',
 'Orenmir',
 'Renewed Skeletal Katana',
 'Warped Iron Scimitar',
 'Verdict',
 "Winter's Bite",
 'Spectral Diamond Doomblade',
 'Stormbringer, Dark Blade of Ending Misery',
 'Final Critic',
 'Victor Iron Spikes',
 'Splinter',
 'Foul Edge',
 'Splitter, Foe Of Subtlety',
 'Stormfury Mace',
 'Deathraze',
 'Ghost Reaver, Longsword of Magic',
 'Mercy, Katana of Dismay',
 'Whistling Mithril Warblade',
 'Spada, Etcher of Hatred',
 'Crucifer',
 'Oathbreaker, Last Hope of the Breaking Storm',
 'Hero Cane',
 'Vengeance Cleaver',
 'Woeful Adamantite Claymore',
 'Singed Onyx Warscythe',
 'Blazefury, Protector of Delusions',
 'Exiled Doomblade',
 'Betrayer',
 'Phantomlight',
 'Despair, Favor of Due Diligence',
 'Torchlight, Bond of Storms',
 'Thirsty Iron Reaver',
 'Dawne',
 'Malice, Legacy of the Queen',
 'Putrid Fan',
 'Thorn, Conqueror of the Corrupted',
 'Possessed Core',
 'Haunted Bronzed Bludgeon',
 'Rage, Legacy of the Lone Victor',
 'Wolf, Promise of the Moonwalker',
 "Gladiator's Glaive",
 'Striker',
 'Blindscythe',
 'Blood Infused Guardian',
 'Avenger',
 "Twilight's Carver",
 'Dreamsong',
 'Bone Crushing Silver Skewer',
 'Hatred',
 'Spectral Bone Axe',
 'Thorn, Satchel of Dark Souls',
 "Faith's Scimitar",
 'The Void, Vengeance of Dark Magic',
 'Eternal Cleaver',
 'Piety, Guardian of Riddles',
 'Fusion Pummel',
 'Suspension',
 'Alpha, Reach of Ending Hope',
 'Darkheart, Butcher of the Champion',
 'War-Forged Gold Deflector',
 'Malificent Bag',
 'Restored Bauble',
 'Tranquility, Razor of Black Magic',
 'Stormfury Longsword',
 'Hopeless Ebon Dualblade',
 'Worldbreaker',
 'Storm-Weaver, Slayer of Inception',
 'Unending Tyranny',
 'Celeste',
 'Blood-Forged Skeletal Spine',
 'Ragnarok',
 'Frenzy, Defender of the Harvest',
 'Persuasion',
 'Deadline, Voice Of Subtlety',
 'Agatha',
 "Solitude's Reaver",
 'Ghastly Adamantite Protector',
 'Unholy Wand',
 'Devine',
 'Endbringer',
 "Warmonger, Gift of Suffering's End",
 'Heartless Bone Dualblade',
 'Massacre',
 'Sun Strike, Jaws of Twisted Visions',
 'Apocalyptic Battlescythe',
 'Lazarus, Terror of the Earth',
 'Primitive Blade',
 'Shadowsteel',
 'Purgatory, Gem of Regret',
 'Fate, Vengeance of Eternal Justice',
 'Sleepwalker',
 'Extraction, Quickblade Of Trembling Hands',
 'Singed Scalpel',
 'Crying Steel Sickle',
 'Yearning Mageblade',
 'Stormfury Lantern',
 'Betrayal, Whisper of Grieving Widows',
 'Undead Crusader',
 "Hope's End",
 'Toothpick',
 "Reaper's Toll",
 'Oathbreaker, Spellblade of Trials',
 'Bonecarvin Battle Axe',
 'Ritual Mace',
 'Wolf',
 'Orbit',
 'The Oculus, Token of Lost Worlds',
 'Fiery Glass Crusader',
 'Relentless Iron Skewer',
 'Flux, Destroyer of Due Diligence',
 'Amnesia',
 'Blade of the Grave',
 'Netherbane',
 'Warped Fetish',
 'Second Chance',
 'Chaos, Ender of the End',
 'Blazeguard, Reach of Eternity',
 'Azurewrath',
 'Dawn',
 'Souleater',
 'Venom Claymore',
 'Alpha, Oath of Zeal',
 'Scalpel',
 'Feral Katana',
 "Misery's End",
 'Demise',
 'Stormcaller',
 "Freak's Bite, Favor of Holy Might",
 'Riddle, Tribute of Ended Dreams',
 'Rusty Skull',
 'Deluge, Edge of the West',
 'Emberling, Defender of Delusions',
 'Foul Titanium Battle Axe',
 'Trickster',
 'Winterthorn, Defender of Shifting Worlds',
 'Exiled Mithril Longsword']

In [140]:
list(set(pymoli2_rename.ItemName))

['Mourning Blade',
 'Vindictive Glass Edge',
 'Heartseeker, Reaver of Souls',
 'Aetherius, Boon of the Blessed',
 'Curved Axe',
 'Conqueror Adamantite Mace',
 'Mercenary Sabre',
 'Thunderfury Scimitar',
 'Glimmer, Ender of the Moon',
 'Dreamkiss',
 'Warped Diamond Crusader',
 'Fury',
 'Alpha',
 'Righteous Might',
 'Yearning Crusher',
 'Soul Infused Crystal',
 'Lifebender',
 'Expiration, Warscythe Of Lost Worlds',
 'Retribution Axe',
 "Bloodlord's Fetish",
 'Heartstriker, Legacy of the Light',
 'Shadow Strike, Glory of Ending Hope',
 'Brimstone',
 "Dragon's Greatsword",
 'Brutality Ivory Warmace',
 'Lightning, Etcher of the King',
 'Glinting Glass Edge',
 'Serenity',
 'Interrogator, Blood Blade of the Queen',
 'Downfall, Scalpel Of The Emperor',
 'Hailstorm Shadowsteel Scythe',
 'Frenzied Scimitar',
 'Celeste, Incarnation of the Corrupted',
 'Piece Maker',
 'Soul-Forged Steel Shortsword',
 'Severance',
 'The Decapitator',
 'Swan Song, Gouger Of Terror',
 'Nirvana',
 'Darkheart',
 'Hellreaver, Heirloom of Inception',
 'Arcane Gem',
 'Pursuit, Cudgel of Necromancy',
 'Abyssal Shard',
 'Orenmir',
 'Renewed Skeletal Katana',
 'Warped Iron Scimitar',
 'Verdict',
 "Winter's Bite",
 'Spectral Diamond Doomblade',
 'Stormbringer, Dark Blade of Ending Misery',
 'Final Critic',
 'Victor Iron Spikes',
 'Splinter',
 'Foul Edge',
 'Splitter, Foe Of Subtlety',
 'Stormfury Mace',
 'Deathraze',
 'Ghost Reaver, Longsword of Magic',
 'Mercy, Katana of Dismay',
 'Whistling Mithril Warblade',
 'Spada, Etcher of Hatred',
 'Crucifer',
 'Oathbreaker, Last Hope of the Breaking Storm',
 'Hero Cane',
 'Vengeance Cleaver',
 'Woeful Adamantite Claymore',
 'Singed Onyx Warscythe',
 'Blazefury, Protector of Delusions',
 'Exiled Doomblade',
 'Betrayer',
 'Phantomlight',
 'Despair, Favor of Due Diligence',
 'Torchlight, Bond of Storms',
 'Thirsty Iron Reaver',
 'Dawne',
 'Malice, Legacy of the Queen',
 'Putrid Fan',
 'Thorn, Conqueror of the Corrupted',
 'Possessed Core',
 'Haunted Bronzed Bludgeon',
 'Rage, Legacy of the Lone Victor',
 'Wolf, Promise of the Moonwalker',
 "Gladiator's Glaive",
 'Striker',
 'Blindscythe',
 'Blood Infused Guardian',
 'Avenger',
 "Twilight's Carver",
 'Dreamsong',
 'Bone Crushing Silver Skewer',
 'Hatred',
 'Spectral Bone Axe',
 'Thorn, Satchel of Dark Souls',
 "Faith's Scimitar",
 'The Void, Vengeance of Dark Magic',
 'Eternal Cleaver',
 'Piety, Guardian of Riddles',
 'Fusion Pummel',
 'Suspension',
 'Alpha, Reach of Ending Hope',
 'Darkheart, Butcher of the Champion',
 'War-Forged Gold Deflector',
 'Malificent Bag',
 'Restored Bauble',
 'Tranquility, Razor of Black Magic',
 'Stormfury Longsword',
 'Hopeless Ebon Dualblade',
 'Worldbreaker',
 'Storm-Weaver, Slayer of Inception',
 'Unending Tyranny',
 'Celeste',
 'Blood-Forged Skeletal Spine',
 'Ragnarok',
 'Frenzy, Defender of the Harvest',
 'Persuasion',
 'Deadline, Voice Of Subtlety',
 'Agatha',
 "Solitude's Reaver",
 'Ghastly Adamantite Protector',
 'Unholy Wand',
 'Devine',
 'Endbringer',
 "Warmonger, Gift of Suffering's End",
 'Heartless Bone Dualblade',
 'Massacre',
 'Sun Strike, Jaws of Twisted Visions',
 'Apocalyptic Battlescythe',
 'Lazarus, Terror of the Earth',
 'Primitive Blade',
 'Shadowsteel',
 'Purgatory, Gem of Regret',
 'Fate, Vengeance of Eternal Justice',
 'Sleepwalker',
 'Extraction, Quickblade Of Trembling Hands',
 'Singed Scalpel',
 'Crying Steel Sickle',
 'Yearning Mageblade',
 'Stormfury Lantern',
 'Betrayal, Whisper of Grieving Widows',
 'Undead Crusader',
 "Hope's End",
 'Toothpick',
 "Reaper's Toll",
 'Oathbreaker, Spellblade of Trials',
 'Bonecarvin Battle Axe',
 'Ritual Mace',
 'Wolf',
 'Orbit',
 'The Oculus, Token of Lost Worlds',
 'Fiery Glass Crusader',
 'Relentless Iron Skewer',
 'Flux, Destroyer of Due Diligence',
 'Amnesia',
 'Blade of the Grave',
 'Netherbane',
 'Warped Fetish',
 'Second Chance',
 'Chaos, Ender of the End',
 'Blazeguard, Reach of Eternity',
 'Azurewrath',
 'Dawn',
 'Souleater',
 'Venom Claymore',
 'Alpha, Oath of Zeal',
 'Scalpel',
 'Feral Katana',
 "Misery's End",
 'Demise',
 'Stormcaller',
 "Freak's Bite, Favor of Holy Might",
 'Riddle, Tribute of Ended Dreams',
 'Rusty Skull',
 'Deluge, Edge of the West',
 'Emberling, Defender of Delusions',
 'Foul Titanium Battle Axe',
 'Trickster',
 'Winterthorn, Defender of Shifting Worlds',
 'Exiled Mithril Longsword']

In [141]:
unique_count = len(pymoli1_rename.ItemName)
unique_count

780

In [142]:
pricesums = sum(pymoli1_rename.Price) + sum(pymoli2_rename.Price)
pricesums

4572.6599999999926

In [143]:
averagepp = pymoli1_rename.Price.mean() + pymoli2_rename.Price.mean()
averagepp

5.862384615384606

In [144]:
total_purchase = len(pymoli1_rename.Price) + len(pymoli2_rename.Price)
total_purchase

1560

In [145]:
total_revenue = pricesums
total_revenue

4572.6599999999926

In [146]:
purchasing_analysis = pd.DataFrame({"Number of Unique Items": [unique_count],
                                   "Average Price": [averagepp],
                                   "Number of Purchases": [total_purchase],
                                   "Total Revenue": [total_revenue]})
purchasing_analysis

   Average Price  Number of Purchases  Number of Unique Items  Total Revenue
0       5.862385                 1560                     780        4572.66

In [147]:
malecount = len(Gender["Male"])

NameError: name 'Gender' is not defined

In [148]:
pymoli1_rename['Gender'].value_counts()

Male                     633
Female                   136
Other / Non-Disclosed     11
Name: Gender, dtype: int64

In [149]:
pymoli2_rename['Gender'].value_counts()

Male                     633
Female                   136
Other / Non-Disclosed     11
Name: Gender, dtype: int64

In [150]:
percentmale = 633/780
percentmale

0.8115384615384615

In [151]:
percentfemale = 136/870
percentfemale

0.15632183908045977

In [152]:
percentother = 11/780
percentother

0.014102564102564103

In [153]:
gender_analysis = pd.DataFrame({"Percent Male": [percentmale],
                                "Percent Female":[percentfemale],
                                "Percent Other":[percentother]})

gender_analysis

   Percent Female  Percent Male  Percent Other
0        0.156322      0.811538       0.014103

In [154]:
mpurchase = pymoli2_pd.groupby(['Gender']['Price']).count()
mpurchase

TypeError: list indices must be integers or slices, not str

In [155]:
avpurprice = pymoli2_pd.groupby(['Gender','Price']).mean()
avpurprice

                              Age  Item ID
Gender                Price
Female                1.02   30.0    105.0
                      1.74   20.0    170.0
                      1.89   16.0      0.0
                      2.26   21.0    108.0
                      2.65   39.0      2.0
                      2.95   23.0    118.0
                      3.64   16.0     94.0
                      3.85   11.0     41.0
                      4.01   36.0    173.0
                      4.12   20.0     90.0
                      4.15   23.0    107.0
                      4.39   23.0     68.0
                      4.71   24.0    117.0
Male                  1.08   29.0    126.0
                      1.29   16.0     98.0
                      1.31   20.5    121.5
                      1.34   25.0    127.0
                      1.36   24.0    174.0
                      1.42    8.0      9.0
                      1.62   32.0     23.0
                      1.77   21.0     82.0
                      1.79   21.5    111.0
                      1.81   35.0     10.0
                      1.84   20.0    104.0
                      1.91   24.0      4.0
                      1.92   24.0     97.0
                      1.94   20.0    158.0
                      1.96   33.0     17.0
                      2.12   23.0    176.0
                      2.15   20.5     75.0
...                           ...      ...
                      2.70   27.5     60.0
                      2.71   16.0    172.0
                      2.77   19.0    180.0
                      2.82   20.0     14.0
                      2.88   33.0    129.0
                      2.92   23.0     91.0
                      2.99   11.0    131.0
                      3.09   17.0     71.0
                      3.25   15.0    167.0
                      3.36   21.0     12.0
                      3.38   28.0     27.0
                      3.58   24.0      6.0
                      3.64   22.5     94.0
                      3.67   28.0      1.0
                      3.75   20.0     18.0
                      4.04   21.0    155.0
                      4.11   22.5    154.0
                      4.12   22.0    135.5
                      4.16   38.0    163.0
                      4.25   36.0    139.0
                      4.28   23.0     70.0
                      4.36    8.0     44.0
                      4.49   27.5     93.0
                      4.53    9.0    156.0
                      4.59   21.0     31.0
                      4.65   40.0    148.0
                      4.71   25.0    117.0
                      4.78   18.0     25.0
                      4.81   25.0     84.0
Other / Non-Disclosed 2.12   12.0    176.0

[65 rows x 2 columns]

In [156]:
totalpv = pymoli2_pd.groupby(['Gender','Price']).sum()
totalpv

                             Age  Item ID
Gender                Price
Female                1.02    30      105
                      1.74    20      170
                      1.89    16        0
                      2.26    21      108
                      2.65    39        2
                      2.95    23      118
                      3.64    16       94
                      3.85    11       41
                      4.01    36      173
                      4.12    20       90
                      4.15    23      107
                      4.39    23       68
                      4.71    24      117
Male                  1.08    58      252
                      1.29    32      196
                      1.31    41      243
                      1.34    25      127
                      1.36    24      174
                      1.42     8        9
                      1.62    32       23
                      1.77    21       82
                      1.79    43      222
                      1.81    35       10
                      1.84    20      104
                      1.91    24        4
                      1.92    24       97
                      1.94    20      158
                      1.96    33       17
                      2.12    23      176
                      2.15    41      150
...                          ...      ...
                      2.70    55      120
                      2.71    16      172
                      2.77    38      360
                      2.82    20       14
                      2.88    33      129
                      2.92    23       91
                      2.99    11      131
                      3.09    17       71
                      3.25    15      167
                      3.36    21       12
                      3.38    28       27
                      3.58    24        6
                      3.64    45      188
                      3.67    28        1
                      3.75    20       18
                      4.04    21      155
                      4.11    45      308
                      4.12    44      271
                      4.16    38      163
                      4.25    36      139
                      4.28    23       70
                      4.36     8       44
                      4.49    55      186
                      4.53     9      156
                      4.59    21       31
                      4.65    40      148
                      4.71    25      117
                      4.78    18       25
                      4.81    25       84
Other / Non-Disclosed 2.12    12      176

[65 rows x 2 columns]

In [157]:
normalized = pymoli2_pd.groupby('Gender')['Price'].count()
normalized

Gender
Female                   13
Male                     64
Other / Non-Disclosed     1
Name: Price, dtype: int64

In [158]:
gender_spending = pd.DataFrame({"Purchase Count": [mpurchase],
                                "Average Purchase Price":[avpurprice],
                                "Total Purchase Value":[totalpv],
                                "Normalized Totals": [normalized]})

gender_spending

,Average Purchase Price,Normalized Totals,Purchase Count,Total Purchase Value
0,Age Item ID Gen...,Gender Female 13 Male ...,Age Item ID Ite...,Age Item ID Gend...

In [159]:
bins = [0, 5, 10, 15, 20, 25, 30, 40]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "40+"]

In [160]:
pcount = pymoli2_pd.groupby("Price")
pcount.max()

,Age,Gender,Item ID,Item Name,SN
Price,,,,,
1.02,30,Female,105,Hailstorm Shadowsteel Scythe,Undosian34
1.08,34,Male,126,Exiled Mithril Longsword,Jiskimsda56
1.29,25,Male,98,"Deadline, Voice Of Subtlety",Undadar97
1.31,24,Male,164,Exiled Doomblade,Yarmol79
1.34,25,Male,127,"Heartseeker, Reaver of Souls",Lirtastan49
1.36,24,Male,174,Primitive Blade,Zhisrisu83
1.42,8,Male,9,"Thorn, Conqueror of the Corrupted",Aiduecal76
1.62,32,Male,23,Crucifer,Hairith93
1.74,20,Female,170,Shadowsteel,Sondassasya91
1.77,21,Male,82,Nirvana,Aidaira26
1.79,25,Male,111,Misery's End,Iskadar31
1.81,35,Male,10,Sleepwalker,Streural92
1.84,20,Male,104,Gladiator's Glaive,Ila44
1.89,16,Female,0,Splinter,Pharithdil38
1.91,24,Male,4,Bloodlord's Fetish,Airi27
1.92,24,Male,97,"Swan Song, Gouger Of Terror",Chaniman66
1.94,20,Male,158,"Darkheart, Butcher of the Champion",Lassimla92
1.96,33,Male,17,"Lazarus, Terror of the Earth",Chanjasksda31
2.12,23,Other / Non-Disclosed,176,Relentless Iron Skewer,Inadeu25
2.15,21,Male,134,Undead Crusader,Syalallodil59
2.22,8,Male,8,"Purgatory, Gem of Regret",Hainaria90
2.26,21,Male,108,"Extraction, Quickblade Of Trembling Hands",Pheodaisun84
2.42,25,Male,64,Fusion Pummel,Undirrasta74
2.55,17,Male,123,Twilight's Carver,Irith83
2.63,32,Male,138,Putrid Fan,Irim47
2.65,39,Female,2,Verdict,Aesririam61
2.70,30,Male,60,Wolf,Sundaky74
2.71,16,Male,172,Blade of the Grave,Shaidanu32
2.77,21,Male,180,Stormcaller,Lisirra44
2.82,20,Male,14,Possessed Core,Frichilsa31
2.88,33,Male,129,"Fate, Vengeance of Eternal Justice",Ethralan59
2.92,23,Male,91,Celeste,Iskossaya95
2.95,23,Female,118,"Ghost Reaver, Longsword of Magic",Assistast50
2.99,11,Male,131,Fury,Eoralphos86
3.09,17,Male,71,Demise,Ilara98
3.25,15,Male,167,"Malice, Legacy of the Queen",Heudai45
3.36,21,Male,12,Dawne,Aidaira26
3.38,28,Male,27,"Riddle, Tribute of Ended Dreams",Undirra90
3.58,24,Male,6,Rusty Skull,Lisosiast26
3.64,23,Male,94,Mourning Blade,Undilsan50
3.67,28,Male,1,Crucifer,Palyon91
3.75,20,Male,18,"Torchlight, Bond of Storms",Eollym91
3.85,11,Female,41,Orbit,Isristira52
4.01,36,Female,173,Stormfury Longsword,Jiskim75
4.04,21,Male,155,War-Forged Gold Deflector,Heulaedru70
4.11,23,Male,154,Feral Katana,Philodil43
4.12,23,Male,181,Reaper's Toll,Yarithrgue83
4.15,23,Female,107,"Splitter, Foe Of Subtlety",Aeri79
4.16,38,Male,163,Thunderfury Scimitar,Ardcil81
4.25,36,Male,139,"Mercy, Katana of Dismay",Aesurstilis64
4.28,23,Male,70,Hope's End,Heosurnuru52
4.36,8,Male,44,Bonecarvin Battle Axe,Yarith71
4.39,23,Female,68,"Storm-Weaver, Slayer of Inception",Firon67
4.49,35,Male,93,Apocalyptic Battlescythe,Iloni35
4.53,9,Male,156,Soul-Forged Steel Shortsword,Rarallo90
4.59,21,Male,31,Trickster,Jiskjask76
4.65,40,Male,148,"Warmonger, Gift of Suffering's End",Aerithllora36
4.71,25,Male,117,"Heartstriker, Legacy of the Light",Sundaky74
4.78,18,Male,25,Hero Cane,Chanirra64
4.81,25,Male,84,Arcane Gem,Eusty71

In [161]:
pcountmean = pcount.mean()
pcountmean

             Age     Item ID
Price
1.02   30.000000  105.000000
1.08   29.000000  126.000000
1.29   16.000000   98.000000
1.31   20.500000  121.500000
1.34   25.000000  127.000000
1.36   24.000000  174.000000
1.42    8.000000    9.000000
1.62   32.000000   23.000000
1.74   20.000000  170.000000
1.77   21.000000   82.000000
1.79   21.500000  111.000000
1.81   35.000000   10.000000
1.84   20.000000  104.000000
1.89   16.000000    0.000000
1.91   24.000000    4.000000
1.92   24.000000   97.000000
1.94   20.000000  158.000000
1.96   33.000000   17.000000
2.12   17.500000  176.000000
2.15   20.500000   75.000000
2.22    8.000000    8.000000
2.26   20.500000  108.000000
2.42   22.500000   64.000000
2.55   17.000000  123.000000
2.63   24.500000   71.500000
2.65   39.000000    2.000000
2.70   27.500000   60.000000
2.71   16.000000  172.000000
2.77   19.000000  180.000000
2.82   20.000000   14.000000
2.88   33.000000  129.000000
2.92   23.000000   91.000000
2.95   23.000000  118.000000
2.99   11.000000  131.000000
3.09   17.000000   71.000000
3.25   15.000000  167.000000
3.36   21.000000   12.000000
3.38   28.000000   27.000000
3.58   24.000000    6.000000
3.64   20.333333   94.000000
3.67   28.000000    1.000000
3.75   20.000000   18.000000
3.85   11.000000   41.000000
4.01   36.000000  173.000000
4.04   21.000000  155.000000
4.11   22.500000  154.000000
4.12   21.333333  120.333333
4.15   23.000000  107.000000
4.16   38.000000  163.000000
4.25   36.000000  139.000000
4.28   23.000000   70.000000
4.36    8.000000   44.000000
4.39   23.000000   68.000000
4.49   27.500000   93.000000
4.53    9.000000  156.000000
4.59   21.000000   31.000000
4.65   40.000000  148.000000
4.71   24.500000  117.000000
4.78   18.000000   25.000000
4.81   25.000000   84.000000

In [162]:
pcounttotal = pcount.sum()
pcounttotal

       Age  Item ID
Price
1.02    30      105
1.08    58      252
1.29    32      196
1.31    41      243
1.34    25      127
1.36    24      174
1.42     8        9
1.62    32       23
1.74    20      170
1.77    21       82
1.79    43      222
1.81    35       10
1.84    20      104
1.89    16        0
1.91    24        4
1.92    24       97
1.94    20      158
1.96    33       17
2.12    35      352
2.15    41      150
2.22     8        8
2.26    41      216
2.42    45      128
2.55    17      123
2.63    49      143
2.65    39        2
2.70    55      120
2.71    16      172
2.77    38      360
2.82    20       14
2.88    33      129
2.92    23       91
2.95    23      118
2.99    11      131
3.09    17       71
3.25    15      167
3.36    21       12
3.38    28       27
3.58    24        6
3.64    61      282
3.67    28        1
3.75    20       18
3.85    11       41
4.01    36      173
4.04    21      155
4.11    45      308
4.12    64      361
4.15    23      107
4.16    38      163
4.25    36      139
4.28    23       70
4.36     8       44
4.39    23       68
4.49    55      186
4.53     9      156
4.59    21       31
4.65    40      148
4.71    49      234
4.78    18       25
4.81    25       84

In [163]:
age_demo = pd.DataFrame({"Percent of Players": [bins],
                                "Total Count":[pcount]})

age_demo

,Percent of Players,Total Count
0,"[0, 5, 10, 15, 20, 25, 30, 40]",<pandas.core.groupby.DataFrameGroupBy object a...

In [164]:
topspend = pymoli2_pd['SN'].groupby(pymoli2_pd['Price']).value_counts().idxmax
topspend

<bound method Series.idxmax of Price  SN
1.02   Undosian34       1
1.08   Chamalo71        1
       Jiskimsda56      1
1.29   Lirtistanya48    1
       Undadar97        1
1.31   Chaniman66       1
       Yarmol79         1
1.34   Lirtastan49      1
1.36   Zhisrisu83       1
1.42   Aiduecal76       1
1.62   Hairith93        1
1.74   Sondassasya91    1
1.77   Aidaira26        1
1.79   Eolideu96        1
       Iskadar31        1
1.81   Streural92       1
1.84   Ila44            1
1.89   Pharithdil38     1
1.91   Airi27           1
1.92   Chaniman66       1
1.94   Lassimla92       1
1.96   Chanjasksda31    1
2.12   Filon68          1
       Inadeu25         1
2.15   Chrathybust28    1
       Syalallodil59    1
2.22   Hainaria90       1
2.26   Airithrin43      1
       Pheodaisun84     1
2.42   Saralp86         1
                       ..
3.38   Undirra90        1
3.58   Lisosiast26      1
3.64   Seostylis96      1
       Sondim43         1
       Undilsan50       1
3.67   Palyon91         1
3.75   Eollym91         1
3.85   Isristira52      1
4.01   Jiskim75         1
4.04   Heulaedru70      1
4.11   Haerithp41       1
       Philodil43       1
4.12   Arithllorin55    1
       Lirtassa77       1
       Yarithrgue83     1
4.15   Aeri79           1
4.16   Ardcil81         1
4.25   Aesurstilis64    1
4.28   Heosurnuru52     1
4.36   Yarith71         1
4.39   Firon67          1
4.49   Chamast86        1
       Iloni35          1
4.53   Rarallo90        1
4.59   Jiskjask76       1
4.65   Aerithllora36    1
4.71   Alarap40         1
       Sundaky74        1
4.78   Chanirra64       1
4.81   Eusty71          1
Name: SN, Length: 78, dtype: int64>

In [165]:
pcount2 = pymoli2_pd['SN'].groupby(pymoli2_pd['Price']).value_counts()
pcount2

Price  SN
1.02   Undosian34       1
1.08   Chamalo71        1
       Jiskimsda56      1
1.29   Lirtistanya48    1
       Undadar97        1
1.31   Chaniman66       1
       Yarmol79         1
1.34   Lirtastan49      1
1.36   Zhisrisu83       1
1.42   Aiduecal76       1
1.62   Hairith93        1
1.74   Sondassasya91    1
1.77   Aidaira26        1
1.79   Eolideu96        1
       Iskadar31        1
1.81   Streural92       1
1.84   Ila44            1
1.89   Pharithdil38     1
1.91   Airi27           1
1.92   Chaniman66       1
1.94   Lassimla92       1
1.96   Chanjasksda31    1
2.12   Filon68          1
       Inadeu25         1
2.15   Chrathybust28    1
       Syalallodil59    1
2.22   Hainaria90       1
2.26   Airithrin43      1
       Pheodaisun84     1
2.42   Saralp86         1
                       ..
3.38   Undirra90        1
3.58   Lisosiast26      1
3.64   Seostylis96      1
       Sondim43         1
       Undilsan50       1
3.67   Palyon91         1
3.75   Eollym91         1
3.85   Isristira52      1
4.01   Jiskim75         1
4.04   Heulaedru70      1
4.11   Haerithp41       1
       Philodil43       1
4.12   Arithllorin55    1
       Lirtassa77       1
       Yarithrgue83     1
4.15   Aeri79           1
4.16   Ardcil81         1
4.25   Aesurstilis64    1
4.28   Heosurnuru52     1
4.36   Yarith71         1
4.39   Firon67          1
4.49   Chamast86        1
       Iloni35          1
4.53   Rarallo90        1
4.59   Jiskjask76       1
4.65   Aerithllora36    1
4.71   Alarap40         1
       Sundaky74        1
4.78   Chanirra64       1
4.81   Eusty71          1
Name: SN, Length: 78, dtype: int64

In [166]:
mean2 = (pymoli2_pd['Price']).mean()
mean2

2.9243589743589733

In [167]:
totalval = pymoli2_pd['SN'].groupby(pymoli2_pd['Price']).sum()
totalval

Price
1.02                             Undosian34
1.08                   Jiskimsda56Chamalo71
1.29                 Lirtistanya48Undadar97
1.31                     Yarmol79Chaniman66
1.34                            Lirtastan49
1.36                             Zhisrisu83
1.42                             Aiduecal76
1.62                              Hairith93
1.74                          Sondassasya91
1.77                              Aidaira26
1.79                     Eolideu96Iskadar31
1.81                             Streural92
1.84                                  Ila44
1.89                           Pharithdil38
1.91                                 Airi27
1.92                             Chaniman66
1.94                             Lassimla92
1.96                          Chanjasksda31
2.12                        Inadeu25Filon68
2.15             Chrathybust28Syalallodil59
2.22                             Hainaria90
2.26                Airithrin43Pheodaisun84
2.42                   Undirrasta74Saralp86
2.55                                Irith83
2.63                        Irim47Hairith93
2.65                            Aesririam61
2.70                    Eustyria89Sundaky74
2.71                             Shaidanu32
2.77                  Chamjaskya75Lisirra44
2.82                            Frichilsa31
2.88                             Ethralan59
2.92                            Iskossaya95
2.95                            Assistast50
2.99                            Eoralphos86
3.09                                Ilara98
3.25                               Heudai45
3.36                              Aidaira26
3.38                              Undirra90
3.58                            Lisosiast26
3.64          Sondim43Seostylis96Undilsan50
3.67                               Palyon91
3.75                               Eollym91
3.85                            Isristira52
4.01                               Jiskim75
4.04                            Heulaedru70
4.11                   Philodil43Haerithp41
4.12    Lirtassa77Arithllorin55Yarithrgue83
4.15                                 Aeri79
4.16                               Ardcil81
4.25                          Aesurstilis64
4.28                           Heosurnuru52
4.36                               Yarith71
4.39                                Firon67
4.49                       Iloni35Chamast86
4.53                              Rarallo90
4.59                             Jiskjask76
4.65                          Aerithllora36
4.71                      Sundaky74Alarap40
4.78                             Chanirra64
4.81                                Eusty71
Name: SN, dtype: object

In [168]:
top_spending = pd.DataFrame({"Purchase Count": [topspend],
                                "Average Purchase Price":[mean2],
                                "Total Purchase Value":[totalval]})

top_spending

,Average Purchase Price,Purchase Count,Total Purchase Value
0,2.924359,<bound method Series.idxmax of Price SN ...,Price 1.02 Undosia...

In [171]:
popitem = pymoli2_pd['Item Name'].value_counts().idxmax()
popitem

'Mourning Blade'

In [172]:
popid = pymoli2_pd['Item ID'].value_counts().idxmax()
popid

94

In [177]:
poppurch = pymoli2_pd['Price'].value_counts().idxmax()
poppurch

3.6400000000000001

In [180]:
totalpurch = pymoli2_pd['Item Name'].groupby(pymoli2_pd['Price']).sum()
totalpurch

Price
1.02                         Hailstorm Shadowsteel Scythe
1.08     Exiled Mithril LongswordExiled Mithril Longsword
1.29    Deadline, Voice Of SubtletyDeadline, Voice Of ...
1.31                  Alpha, Oath of ZealExiled Doomblade
1.34                         Heartseeker, Reaver of Souls
1.36                                      Primitive Blade
1.42                    Thorn, Conqueror of the Corrupted
1.62                                             Crucifer
1.74                                          Shadowsteel
1.77                                              Nirvana
1.79                             Misery's EndMisery's End
1.81                                          Sleepwalker
1.84                                   Gladiator's Glaive
1.89                                             Splinter
1.91                                   Bloodlord's Fetish
1.92                          Swan Song, Gouger Of Terror
1.94                   Darkheart, Butcher of the Champion
1.96                         Lazarus, Terror of the Earth
2.12         Relentless Iron SkewerRelentless Iron Skewer
2.15                       Restored BaubleUndead Crusader
2.22                             Purgatory, Gem of Regret
2.26    Extraction, Quickblade Of Trembling HandsExtra...
2.42                           Fusion PummelFusion Pummel
2.55                                    Twilight's Carver
2.63             Putrid FanPeacekeeper, Wit of Dark Magic
2.65                                              Verdict
2.70                                             WolfWolf
2.71                                   Blade of the Grave
2.77                               StormcallerStormcaller
2.82                                       Possessed Core
2.88                   Fate, Vengeance of Eternal Justice
2.92                                              Celeste
2.95                     Ghost Reaver, Longsword of Magic
2.99                                                 Fury
3.09                                               Demise
3.25                          Malice, Legacy of the Queen
3.36                                                Dawne
3.38                      Riddle, Tribute of Ended Dreams
3.58                                          Rusty Skull
3.64           Mourning BladeMourning BladeMourning Blade
3.67                                             Crucifer
3.75                           Torchlight, Bond of Storms
3.85                                                Orbit
4.01                                  Stormfury Longsword
4.04                            War-Forged Gold Deflector
4.11                             Feral KatanaFeral Katana
4.12                        BetrayerBetrayerReaper's Toll
4.15                            Splitter, Foe Of Subtlety
4.16                                 Thunderfury Scimitar
4.25                              Mercy, Katana of Dismay
4.28                                           Hope's End
4.36                                Bonecarvin Battle Axe
4.39                    Storm-Weaver, Slayer of Inception
4.49     Apocalyptic BattlescytheApocalyptic Battlescythe
4.53                         Soul-Forged Steel Shortsword
4.59                                            Trickster
4.65                   Warmonger, Gift of Suffering's End
4.71    Heartstriker, Legacy of the LightHeartstriker,...
4.78                                            Hero Cane
4.81                                           Arcane Gem
Name: Item Name, dtype: object

In [181]:
popularitem = pd.DataFrame({"Item ID": [popid],
                                "Item Name":[popitem],
                                "Purchase Count":[poppurch],
                                "Purchase Values": [totalpurch]})

popularitem

,Item ID,Item Name,Purchase Count,Purchase Values
0,94,Mourning Blade,3.64,Price 1.02 Hailstorm S...

In [211]:
profit_item = pymoli2_pd['Item Name'].groupby(pymoli2_pd['Price']).value_counts()
profit_item

Price  Item Name
1.02   Hailstorm Shadowsteel Scythe                 1
1.08   Exiled Mithril Longsword                     2
1.29   Deadline, Voice Of Subtlety                  2
1.31   Alpha, Oath of Zeal                          1
       Exiled Doomblade                             1
1.34   Heartseeker, Reaver of Souls                 1
1.36   Primitive Blade                              1
1.42   Thorn, Conqueror of the Corrupted            1
1.62   Crucifer                                     1
1.74   Shadowsteel                                  1
1.77   Nirvana                                      1
1.79   Misery's End                                 2
1.81   Sleepwalker                                  1
1.84   Gladiator's Glaive                           1
1.89   Splinter                                     1
1.91   Bloodlord's Fetish                           1
1.92   Swan Song, Gouger Of Terror                  1
1.94   Darkheart, Butcher of the Champion           1
1.96   Lazarus, Terror of the Earth                 1
2.12   Relentless Iron Skewer                       2
2.15   Restored Bauble                              1
       Undead Crusader                              1
2.22   Purgatory, Gem of Regret                     1
2.26   Extraction, Quickblade Of Trembling Hands    2
2.42   Fusion Pummel                                2
2.55   Twilight's Carver                            1
2.63   Peacekeeper, Wit of Dark Magic               1
       Putrid Fan                                   1
2.65   Verdict                                      1
2.70   Wolf                                         2
                                                   ..
2.92   Celeste                                      1
2.95   Ghost Reaver, Longsword of Magic             1
2.99   Fury                                         1
3.09   Demise                                       1
3.25   Malice, Legacy of the Queen                  1
3.36   Dawne                                        1
3.38   Riddle, Tribute of Ended Dreams              1
3.58   Rusty Skull                                  1
3.64   Mourning Blade                               3
3.67   Crucifer                                     1
3.75   Torchlight, Bond of Storms                   1
3.85   Orbit                                        1
4.01   Stormfury Longsword                          1
4.04   War-Forged Gold Deflector                    1
4.11   Feral Katana                                 2
4.12   Betrayer                                     2
       Reaper's Toll                                1
4.15   Splitter, Foe Of Subtlety                    1
4.16   Thunderfury Scimitar                         1
4.25   Mercy, Katana of Dismay                      1
4.28   Hope's End                                   1
4.36   Bonecarvin Battle Axe                        1
4.39   Storm-Weaver, Slayer of Inception            1
4.49   Apocalyptic Battlescythe                     2
4.53   Soul-Forged Steel Shortsword                 1
4.59   Trickster                                    1
4.65   Warmonger, Gift of Suffering's End           1
4.71   Heartstriker, Legacy of the Light            2
4.78   Hero Cane                                    1
4.81   Arcane Gem                                   1
Name: Item Name, Length: 64, dtype: int64

In [213]:
item_id = pymoli2_pd['Item ID'].groupby(pymoli2_pd['Price']).value_counts()
item_id

Price  Item ID
1.02   105        1
1.08   126        2
1.29   98         2
1.31   79         1
       164        1
1.34   127        1
1.36   174        1
1.42   9          1
1.62   23         1
1.74   170        1
1.77   82         1
1.79   111        2
1.81   10         1
1.84   104        1
1.89   0          1
1.91   4          1
1.92   97         1
1.94   158        1
1.96   17         1
2.12   176        2
2.15   16         1
       134        1
2.22   8          1
2.26   108        2
2.42   64         2
2.55   123        1
2.63   5          1
       138        1
2.65   2          1
2.70   60         2
                 ..
2.92   91         1
2.95   118        1
2.99   131        1
3.09   71         1
3.25   167        1
3.36   12         1
3.38   27         1
3.58   6          1
3.64   94         3
3.67   1          1
3.75   18         1
3.85   41         1
4.01   173        1
4.04   155        1
4.11   154        2
4.12   90         2
       181        1
4.15   107        1
4.16   163        1
4.25   139        1
4.28   70         1
4.36   44         1
4.39   68         1
4.49   93         2
4.53   156        1
4.59   31         1
4.65   148        1
4.71   117        2
4.78   25         1
4.81   84         1
Name: Item ID, Length: 64, dtype: int64

In [214]:
pcount3 = pymoli2_pd['Item Name'].groupby(pymoli2_pd['Price']).value_counts()
pcount3

Price  Item Name
1.02   Hailstorm Shadowsteel Scythe                 1
1.08   Exiled Mithril Longsword                     2
1.29   Deadline, Voice Of Subtlety                  2
1.31   Alpha, Oath of Zeal                          1
       Exiled Doomblade                             1
1.34   Heartseeker, Reaver of Souls                 1
1.36   Primitive Blade                              1
1.42   Thorn, Conqueror of the Corrupted            1
1.62   Crucifer                                     1
1.74   Shadowsteel                                  1
1.77   Nirvana                                      1
1.79   Misery's End                                 2
1.81   Sleepwalker                                  1
1.84   Gladiator's Glaive                           1
1.89   Splinter                                     1
1.91   Bloodlord's Fetish                           1
1.92   Swan Song, Gouger Of Terror                  1
1.94   Darkheart, Butcher of the Champion           1
1.96   Lazarus, Terror of the Earth                 1
2.12   Relentless Iron Skewer                       2
2.15   Restored Bauble                              1
       Undead Crusader                              1
2.22   Purgatory, Gem of Regret                     1
2.26   Extraction, Quickblade Of Trembling Hands    2
2.42   Fusion Pummel                                2
2.55   Twilight's Carver                            1
2.63   Peacekeeper, Wit of Dark Magic               1
       Putrid Fan                                   1
2.65   Verdict                                      1
2.70   Wolf                                         2
                                                   ..
2.92   Celeste                                      1
2.95   Ghost Reaver, Longsword of Magic             1
2.99   Fury                                         1
3.09   Demise                                       1
3.25   Malice, Legacy of the Queen                  1
3.36   Dawne                                        1
3.38   Riddle, Tribute of Ended Dreams              1
3.58   Rusty Skull                                  1
3.64   Mourning Blade                               3
3.67   Crucifer                                     1
3.75   Torchlight, Bond of Storms                   1
3.85   Orbit                                        1
4.01   Stormfury Longsword                          1
4.04   War-Forged Gold Deflector                    1
4.11   Feral Katana                                 2
4.12   Betrayer                                     2
       Reaper's Toll                                1
4.15   Splitter, Foe Of Subtlety                    1
4.16   Thunderfury Scimitar                         1
4.25   Mercy, Katana of Dismay                      1
4.28   Hope's End                                   1
4.36   Bonecarvin Battle Axe                        1
4.39   Storm-Weaver, Slayer of Inception            1
4.49   Apocalyptic Battlescythe                     2
4.53   Soul-Forged Steel Shortsword                 1
4.59   Trickster                                    1
4.65   Warmonger, Gift of Suffering's End           1
4.71   Heartstriker, Legacy of the Light            2
4.78   Hero Cane                                    1
4.81   Arcane Gem                                   1
Name: Item Name, Length: 64, dtype: int64

In [217]:
price3 = pymoli2_pd['Item Name'].groupby(pymoli2_pd['Price']).value_counts().idxmax()
price3

(3.6400000000000001, 'Mourning Blade')

In [222]:
totalpv3 = pymoli2_pd['Item Name'].groupby(pymoli2_pd['Price']).sum()
totalpv3

Price
1.02                         Hailstorm Shadowsteel Scythe
1.08     Exiled Mithril LongswordExiled Mithril Longsword
1.29    Deadline, Voice Of SubtletyDeadline, Voice Of ...
1.31                  Alpha, Oath of ZealExiled Doomblade
1.34                         Heartseeker, Reaver of Souls
1.36                                      Primitive Blade
1.42                    Thorn, Conqueror of the Corrupted
1.62                                             Crucifer
1.74                                          Shadowsteel
1.77                                              Nirvana
1.79                             Misery's EndMisery's End
1.81                                          Sleepwalker
1.84                                   Gladiator's Glaive
1.89                                             Splinter
1.91                                   Bloodlord's Fetish
1.92                          Swan Song, Gouger Of Terror
1.94                   Darkheart, Butcher of the Champion
1.96                         Lazarus, Terror of the Earth
2.12         Relentless Iron SkewerRelentless Iron Skewer
2.15                       Restored BaubleUndead Crusader
2.22                             Purgatory, Gem of Regret
2.26    Extraction, Quickblade Of Trembling HandsExtra...
2.42                           Fusion PummelFusion Pummel
2.55                                    Twilight's Carver
2.63             Putrid FanPeacekeeper, Wit of Dark Magic
2.65                                              Verdict
2.70                                             WolfWolf
2.71                                   Blade of the Grave
2.77                               StormcallerStormcaller
2.82                                       Possessed Core
2.88                   Fate, Vengeance of Eternal Justice
2.92                                              Celeste
2.95                     Ghost Reaver, Longsword of Magic
2.99                                                 Fury
3.09                                               Demise
3.25                          Malice, Legacy of the Queen
3.36                                                Dawne
3.38                      Riddle, Tribute of Ended Dreams
3.58                                          Rusty Skull
3.64           Mourning BladeMourning BladeMourning Blade
3.67                                             Crucifer
3.75                           Torchlight, Bond of Storms
3.85                                                Orbit
4.01                                  Stormfury Longsword
4.04                            War-Forged Gold Deflector
4.11                             Feral KatanaFeral Katana
4.12                        BetrayerBetrayerReaper's Toll
4.15                            Splitter, Foe Of Subtlety
4.16                                 Thunderfury Scimitar
4.25                              Mercy, Katana of Dismay
4.28                                           Hope's End
4.36                                Bonecarvin Battle Axe
4.39                    Storm-Weaver, Slayer of Inception
4.49     Apocalyptic BattlescytheApocalyptic Battlescythe
4.53                         Soul-Forged Steel Shortsword
4.59                                            Trickster
4.65                   Warmonger, Gift of Suffering's End
4.71    Heartstriker, Legacy of the LightHeartstriker,...
4.78                                            Hero Cane
4.81                                           Arcane Gem
Name: Item Name, dtype: object

In [226]:
most_profit = pd.DataFrame({"Item Name": [profit_item],
                                "Item ID":[item_id],
                                "Purchase Count":[pcount3],
                                "Item Price":[price3],
                                "Total Purchase Value":[totalpv3]})

most_profit

,Item ID,Item Name,Item Price,Purchase Count,Total Purchase Value
0,Price Item ID 1.02 105 1 1.08 126 ...,Price Item Name ...,"(3.64, Mourning Blade)",Price Item Name ...,Price 1.02 Hailstorm S...